spring:
  datasource:
    url: jdbc:mysql://localhost:3307/restaurante-reservas
    username: user
    password: admin

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
      format_sql: true
